In [2]:
import numpy as np
import time

### create array from list

In [3]:
arr_1d=np.array([1,2,3,4,5])
print(arr_1d)
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### list vs numpy array

In [4]:
py_list=[1,2,3]
print(py_list*2)
np_array=np.array([1,2,3])
print(np_array*2)
start=time.time()
py_list=[i*2 for i in range(10000000)]
print(time.time()-start)
start=time.time()
np_array=np.arange(10000000)
print(time.time()-start)

[1, 2, 3, 1, 2, 3]
[2 4 6]
3.73199462890625
0.3509986400604248


### creating array from scratch

In [ ]:
zeros=np.zeros((3,4))
print(zeros)
ones=np.ones((2,3))
print(ones)
full=np.full((2,2),7)
print(full)
random=np.random.random((2,3))
print(random)
sequence=np.arange(0,9)
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[0.07864094 0.96196559 0.92630331]
 [0.09546457 0.80310313 0.78850671]]
[0 1 2 3 4 5 6 7 8]


### Vector, Matrix, Tensor

In [23]:
vector=np.array([1,2,3])
print(vector)
matrix=np.array([[1,2,3],[4,5,6]])
print(matrix)
tensor=np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])
print(tensor)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [ ]:
arr=np.array([[1,2],[3,4]])
# arr=np.array([[1,2],[3,4.1]])
# arr=np.array([[1,2],[3,'4.1']])
# arr=np.array([[1,2],[3,True]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 2)
2
4
int64


### Array Reshaping

In [35]:
arr=np.arange(12)
print(arr)
reshaped=arr.reshape((3,4))
print(reshaped)
flattened=reshaped.flatten()
print(flattened)
raveled=reshaped.ravel() # returns view, instead of copy
print(raveled)
transpose=reshaped.T
print(transpose)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
