## Numpy Array Operations

In [2]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4,5,6,6,7,8,9,10])
print(arr[2:7])
print(arr[1:8:2])
print(arr[-3])

[3 4 5 6 6]
[2 4 6 7]
8


In [10]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[1,2])
print(arr2d[1])
print(arr2d[:,1])

6
[4 5 6]
[2 5 8]


## Sorting

In [15]:
a=np.array([4,24,42,35,7,2,1,54])
print(np.sort(a))
a2=np.array([[3,1],[1,2],[2,3]])
print(np.sort(a2,axis=0))
print(np.sort(a2,axis=1))
print(np.sort(a2))

[ 1  2  4  7 24 35 42 54]
[[1 1]
 [2 2]
 [3 3]]
[[1 3]
 [1 2]
 [2 3]]
[[1 3]
 [1 2]
 [2 3]]


## Filter

In [16]:
n=np.array([1,2,3,4,5,6,7,8,9])
print(n[n%2==0])

[2 4 6 8]


## Filter with mask

In [17]:
mask=n>5
print(n[mask])

[6 7 8 9]


## Fancy indexing vs np.where()

In [21]:
indices=[0,2,4]
print(n[indices])
print(n[np.where(n>5)])

[1 3 5]
[6 7 8 9]


In [23]:
print(np.where(n>5,n*2,n))
print(np.where(n>5,True,False))

[ 1  2  3  4  5 12 14 16 18]
[False False False False False  True  True  True  True]


### Adding, Removing Data

In [26]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1+arr2)
print(np.concatenate(((arr1,arr2))))

[5 7 9]
[1 2 3 4 5 6]


### Array Compatibility

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
print(a.shape,b.shape)

(1, 1, 3) (3,)


In [34]:
orig=np.array([[1,2],[3,4]])
newRow=np.array([5,6])
withNewRow=np.vstack((orig,newRow))
print(withNewRow)
newCol=np.array([[7],[8]])
withNewCol=np.hstack((orig,newCol))
print(withNewCol)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


### Deletion

In [36]:
arr=np.array([1,2,3,4,5])
deleted=np.delete(arr,2)
print(deleted,arr)

[1 2 4 5] [1 2 3 4 5]
